Add Swift 6 support. Refine historyTokenStorage implementation.
yonat/ContactsChangeNotifier pull request #7
Opened 2024-09-28 18:57 UTC by JPToroDev

2024-10-06 14:20 UTC, JPToroDev commented
Hi @yonat, just wanted to check in and see if you have any questions or concerns about my pull request.

2024-10-06 14:39 UTC, yonat commented
Sorry, I have been too busy... will take a look on Friday.

2024-10-06 14:48 UTC, JPToroDev commented
Sounds good—thank you!

2024-10-17 23:29 UTC, JPToroDev commented
Hey @yonat. Just wanted to circle back here and see if there's any update on the pull request.

2024-10-19 16:02 UTC, yonat requested changes
Hi, thanks so much! I left some stylistic comments, still need to run and test this.

2024-10-19 16:02 UTC, yonat commented on Package.swift
> -// swift-tools-version:5.6
I prefer to keep Xcode 15 support.

2024-10-19 16:02 UTC, yonat commented on Package.swift
> -            resources: [.copy("PrivacyInfo.xcprivacy")]
Thanks, but this change is already part of `main` - please rebase on the latest commit.

2024-10-19 16:02 UTC, yonat commented on Sources/ContactsChangeNotifier/ContactsChangeNotifier.swift
> +
Lot's of these little formatting changes - did you disable SwiftLint and SwiftFormat? They should take care of it.

2024-10-19 16:02 UTC, yonat commented on Sources/ContactsChangeNotifier/ContactsChangeNotifier.swift
> +        includeGroupChanges: Bool = true,
Nice, tx.

2024-10-19 16:02 UTC, yonat commented on Sources/ContactsChangeNotifier/ContactsChangeNotifier.swift
> +            switch self {
Really, no need for `HistoryTokenStorageType` now, it can all be just `HistoryTokenStorage` and have concrete subclasses for UserDefaults and iCloud. We Swift-programmers tend to over-use `switch`, but many times good old protocols and classes are enough.

We can still have `.userDefaults()` as a static func of the protocol, so the init default value will stay the same.

2024-10-19 17:28 UTC, JPToroDev commented on Sources/ContactsChangeNotifier/ContactsChangeNotifier.swift
> +            switch self {
Good idea. I think I've interpreted what you're asking for correctly. Take a look and let me know if I need to make any tweaks. All your other notes have been addressed—many nice catches, thank you!

2024-10-19 17:35 UTC, JPToroDev commented
Just pushed a new commit with your requested revisions. Let me know if you need anything else after you run and test!

2024-10-19 20:00 UTC, yonat commented
Cool! Would you allow me to make changes to this PR? I have some stylistic modifications and I think it would be easier if I just do them.

2024-10-19 20:05 UTC, JPToroDev commented
Excited to see them—go for it!

2024-10-20 06:09 UTC, yonat commented
Thanks, please review the last 3 commits and see if it's okay by you.

2024-10-20 12:50 UTC, JPToroDev commented
Very nice—especially the simplification of HistoryTokenStorage. One question: why go with classes over structs for its concrete implementations? Wouldn't structs be more lightweight?

2024-10-20 16:15 UTC, yonat commented
If it's a struct then `historyTokenStorage` has to be a `var` and not a `let`, which results in warning:
> Stored property 'historyTokenStorage' of 'Sendable'-conforming class 'ContactsChangeNotifier' is mutable; this is an error in the Swift 6 language mode

2024-10-20 16:37 UTC, JPToroDev commented
Ah I see, don't know why that error didn't come up on my end. Everything looks great—thanks again for the improvements.

2024-10-20 19:13 UTC, merged